version: '3'
services:
  mongodb:
    image: niranganiluminda/mongodb:${BUILD_NUMBER}
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always
  
  app:
    image: niranganiluminda/build-linux-4-11:${BUILD_NUMBER}
    container_name: my_app
    depends_on:
      - mongodb
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/travel-booking-app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
    
volumes:
  mongodb_data: